### ISSUE TITLE
问一个初级的编译打包的问题

### ISSUE THREAD

**Issue by ganluo960214** [owent/bash-shell#1]
我想在A机编译一个gcc 给B机用 

在A机(centos)上使用gcc4.8编译gcc.6.2.0完成，安装成功。想要移植到B机上但是部分头文件没有移植。

A机
编译，安装过程：

    ./configure --enable-threads=posix --disable-multilib --enable-languages=c,c++;\
    make -j6 && echo $(date +%s) > "make_install_date" && make install

打包过程（通过find 查看 某个时间段 变化 的 文件）：
    
    echo $(find /usr -path /usr/local/src -prune -o ! -type d -mmin -$(expr $(expr $(date +%s) - $(cat make_install_date)) / 60 + 1) | grep -v /usr/local/src) > "filesPath";\
    tar -czf gcc-6.2.0.maked.tar.gz $(cat filesPath) && tar -czf gcc-6.2.0.maked.install.package.tar.gz gcc-6.2.0.maked.tar.gz filesPath

复制 gcc-6.2.0.maked.install.package.tar.gz 到 B机 解压 覆盖文件 使用gcc.6.2.0， B机需要gcc高版本。

编译B机项目时缺少 locale.h 头文件

回到A机：
    
    find / -name locale.h
    /usr/local/src/gcc/gcc-6.2.0/libstdc++-v3/include/c_compatibility/locale.h

发现并没有安装

请教如何移植到B机？是编译参数不对吗？

从你的blog来。

**Comment by owent** [comment]
@GanLuo96214  编译出来的gcc的查找目录并不是源码目录，而是prefix目录。

你可以通过
```bash
echo | g++ -x c++ -v -E -
```
来查看GCC的查找目录，然后来确定要打包哪些目录，另外还有库文件，命令是：
```bash
g++ --print-search-dirs
```

不是所有的目录都需要打包，有一些是系统目录共享的。另外还有帮助文档和一些其他的东西你需要自己找一下。

还有，让你编译的gcc替换掉系统自带的gcc是个很危险的行为，因为可能会破坏很多yum包的接口依赖。所以一般是会让自己编译的包与yum安装的包共存。建议你用 https://github.com/owent-utils/bash-shell/blob/master/GCC%20Installer/gcc-6/installer.sh 编译完直接打包prefix目录（默认是 /usr/local/gcc-6.3.0 ）

**Comment by ganluo960214** [comment]
我找到问题了是 glibc 需要高版本。
