### ISSUE TITLE
enable-languages=ada的问题

### ISSUE THREAD

**Issue by textworld** [owent/bash-shell#2]
你好，我在编译安装gcc-7.1.0的时候遇到以下问题
```
root@ubunut:/home/gcc-7.1.0# ./configure --enable-languages=c,c++,ada
configure: error: GNAT is required to build ada
```
但是我已经通过apt-get install gnat安装了 GNAT,请问是否遇到这个问题？

**Comment by owent** [comment]
@textworld 我这个主要用于CentOS/Fedora/Redhat的。你用apt的包管理依赖库检测和路径可能会有问题
另外ada的话请参考下gcc的文档。有些语言的依赖库是必须要固定某个版本的。默认只会检测到能便宜就编译，不能就不编译。我这里的脚本只保证一定能编译c/c++

**Comment by textworld** [comment]
经过测试，得下载GNAT GPL 2016，而不能使用apt-get install gnat。
下载地址：[gnat-gpl-2016-x86_64-linux-bin.tar.gz](http://libre.adacore.com/download/configurations)，下载的是二进制版本，373MB。
安装方法
```
cd gnat-gpl-2016-x86_64-linux-bin 
./doinstall #默认安装地址位/usr/gnat
export $PATH=/usr/gnat/bin:$PATH #这一步是为了替代老的gnat，必须把/usr/gnat/bin写在$PATH之前
cd ..
```
安装好后
```
root@ubuntu:/home# gnatmake --version | head -n 1
GNATMAKE GPL 2016 (20160515-49)
```
再去编译gcc，就不会出现configure: error: GNAT is required to build ada的错误了。
我的环境
```
root@ubuntu:/home# uname -a
Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by owent** [comment]
@textworld 突然想起来，如果有gnat-dev这个包的话。你用apt-get install gnat-dev 也许可以
