### ISSUE TITLE
能不能将你的Centos7编译环境.OVA文件上传到百度网盘,我的Centos7环境总是有问题,编译过程很多错误

### ISSUE THREAD

**Issue by sun363587351** [owent/bash-shell#4]
能不能将你的Centos7编译环境.OVA文件上传到百度网盘,我的Centos7环境总是有问题,编译过程很多错误

**Comment by owent** [comment]
https://github.com/owent-utils/docker-setup/blob/main/centos7.devtools.Dockerfile
我的初始化脚本基本就是这个。你可以造着跑一下安装开发工具包。

**Comment by sun363587351** [comment]
gcc或者llvm编译环境还是基于https://github.com/owent-utils/docker-setup/blob/main/centos7.devtools.Dockerfile吗？每次环境搭建问题太多了，谢谢

**Comment by owent** [comment]
> https://github.com/owent-utils/docker-setup/blob/main/centos7.devtools.Dockerfile 我的初始化脚本基本就是这个。你可以造着跑一下安装开发工具包。

我们目前不是这个，这个比较老了，只有写基本的工具。
我们现在很多工具都是自己编译的，我们内部用的发行版是基于CentOS 7的但是和CentOS 7不完全一样，生成完的镜像大约10GB，都是传到我们内部的仓库里的。你可以参考下下面这个回复里的脚本，这是我们内部用的构建脚本，然后已经把私有的内容抹除了。

https://github.com/owent-utils/bash-shell/issues/5#issuecomment-1126723034

另外请确保能稳定访问到 github.com , gomirrors.org（或者换成可以访问的地址或者去掉golang的部分）, llvm.org, dl.k8s.io, sourceware.org, kernel.org, nodejs.org, packages.microsoft.com
